---
- name: Pre-flight
  ansible.builtin.include_tasks: pre_flight.yml

- name: Proxmox node configuration
  ansible.builtin.include_tasks: configuration.yml
  when: proxmox_allow_node_configuration

- name: Register defined and existing VM's
  ansible.builtin.include_tasks: vm_registration.yml

- name: Provision VM's
  ansible.builtin.include_tasks: vm_provision.yml
  when: "'proxmox_provision_' + inventory_hostname in groups"

- name: Deprovision VM's
  ansible.builtin.include_tasks: vm_deprovision.yml
  when: "'proxmox_deprovision_' + inventory_hostname in groups"

# - name: Update VM's according to specs in inventory
#   ansible.builtin.include_tasks: vm_update.yml
#   loop: "{{ groups.servers }}"
